DEBUG    twister_harness.device.factory:factory.py:37 Get device type "hardware"
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa8546e0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa81cb00> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa664910>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'188'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'projects 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:53:31 GMT'), (b'x-kong-upstream-latency', b'16'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa666350>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa81d010> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa809ba0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'287'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:53:31 GMT'), (b'x-kong-upstream-latency', b'15'), (b'x-kong-proxy-latency', b'3'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa80a190>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa81d2e0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa6605f0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'201'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:53:32 GMT'), (b'x-kong-upstream-latency', b'17'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices/68f5880b81db3c0394bbda3a/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.hardware_adapter:utils.py:37 Flashing command: /root/venv/bin/west flash --skip-rebuild --build-dir /__w/golioth-firmware-sdk/golioth-firmware-sdk/twister-out/esp32_devkitc_esp32_procpu/zephyr/lightdb/set/sample.golioth.lightdb_set -- --esp-tool=/root/venv/bin/esptool.py --esp-device=/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_90568bbbd827ee11b31a14d8f49e3369-if00-port0
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:135 Flashing finished
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_90568bbbd827ee11b31a14d8f49e3369-if00-port0
DEBUG    twister_harness.helpers.utils:utils.py:22 Found matching key: CONFIG_SHELL_PROMPT_UART="uart:~$ "
INFO     twister_harness.fixtures:fixtures.py:78 Wait for prompt
DEBUG    twister_harness.helpers.shell:shell.py:49 Got prompt
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa679040>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa7700e0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa679150>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'2'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:53:50 GMT'), (b'x-kong-upstream-latency', b'4'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: DELETE https://api.golioth.io/v1/projects/firmware_ci/devices/68f5880b81db3c0394bbda3a/data/counter "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa831450>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa81db50> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa831e50>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'203'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'credentials 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:53:53 GMT'), (b'x-kong-upstream-latency', b'56'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/devices/68f5880b81db3c0394bbda3a/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [msettings set golioth/psk-id generated-qKUnRWkXmVDFkYEC@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id to generated-qKUnRWkXmVDFkYEC@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id saved as generated-qKUnRWkXmVDFkYEC@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [msettings set golioth/psk generated-qKUnRWkXmVDFkYEC
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk to generated-qKUnRWkXmVDFkYEC
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk saved as generated-qKUnRWkXmVDFkYEC
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred add -k 1 -s "***SAMS_ORANGE_PI_WIFI_SSID***" -p "***SAMS_ORANGE_PI_WIFI_PSK***"
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred auto_connect
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:05.088,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:06.088,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:06.090,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:07.091,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:07.093,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:08.093,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.095,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:09.095,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:09.099,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:10.099,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.102,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.485,000] [0m<inf> net_dhcpv4: Received: 192.168.0.119[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnected
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.486,000] [0m<inf> golioth_mbox: Mbox created, bufsize: 1408, num_items: 10, item_size: 128[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.688,000] [0m<inf> golioth_coap_client_zephyr: Golioth CoAP client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.688,000] [0m<dbg> lightdb_set: main: Setting counter to 0[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.688,000] [0m<dbg> lightdb_set: main: Before request (async)[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.689,000] [0m<dbg> lightdb_set: main: After request (async)[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.689,000] [0m<inf> lightdb_set: Golioth client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.689,000] [0m<inf> golioth_coap_client_zephyr: Entering CoAP I/O loop[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:10.947,000] [0m<dbg> lightdb_set: counter_set_handler: Counter successfully set[0m
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.failed exception=ConnectError(gaierror(-5, 'No address associated with hostname'))
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:190 Closed serial connection for /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_90568bbbd827ee11b31a14d8f49e3369-if00-port0
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa941040>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffaa81d520> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffaa941130>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'2'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Mon, 20 Oct 2025 00:54:06 GMT'), (b'x-kong-upstream-latency', b'37'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: DELETE https://api.golioth.io/v1/projects/firmware_ci/devices/68f5880b81db3c0394bbda3a "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete